name: dermatocare
favicon: null
layout_spectrum: 0.99916
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#ffff00'
    - '#808080'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.501096504740417
  rhythmicContrast: 0.5
purpose: []
